# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('cnpj', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=200)),
                ('CEP', models.CharField(max_length=200)),
                ('complemento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompensacaoHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidadeHoras', models.IntegerField()),
                ('justificativa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraChegada', models.DateTimeField()),
                ('dataHoraSaida', models.DateTimeField()),
                ('justificativaChegada', models.CharField(max_length=255)),
                ('justificativaSaida', models.CharField(max_length=255)),
                ('localizacaoChegada', models.CharField(max_length=255)),
                ('localizacaoSaida', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('observacao', models.CharField(max_length=255)),
                ('horarioRequisitado', models.DateTimeField()),
                ('horarioInicial', models.DateTimeField()),
                ('HorarioFinal', models.DateTimeField()),
                ('statusTarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.StatusTarefa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ponto',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Usuario'),
        ),
        migrations.AddField(
            model_name='compensacaohora',
            name='idAdmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_admin', to='backend.Usuario'),
        ),
        migrations.AddField(
            model_name='compensacaohora',
            name='idFuncionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_funcionario', to='backend.Usuario'),
        ),
    ]
